CREATE DATABASE IF NOT EXISTS jira;

CREATE USER 'jira'@'%' IDENTIFIED BY 'JIRA_MYSQL_PASSWORD';
GRANT ALTER, CREATE, DELETE, DROP, INDEX, INSERT, SELECT, UPDATE ON `jira`.* TO 'jira'@'%';

CREATE DATABASE IF NOT EXISTS mattermost;

CREATE USER 'mmuser'@'%' IDENTIFIED BY 'MATTERMOST_MYSQL_PASSWORD';
GRANT ALTER, CREATE, DELETE, DROP, INDEX, INSERT, SELECT, UPDATE ON `mattermost`.* TO 'mmuser'@'%';

FLUSH PRIVILEGES;